spring:
  application:
    name: configserver
  profiles:
    active: jdbc
  datasource:
    url: jdbc:mysql://localhost:3306/configdb
    username: ${USER}
    password: ${PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    config:
      server:
        jdbc:
          sql: "SELECT PROP_KEY, PROP_VALUE from PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=?"
          default-label: main
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/faisal-courses/app-configuration
#          username: ${GIT_USER}
#          password: ${GIT_TOKEN}
server:
  port: 8888