spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/faisal-courses/app-configuration
          username: ${GIT_USER}
          password: ${GIT_TOKEN}
server:
  port: 8888